### ISSUE TITLE
Installing 2.0.0.0 from PowerShell gallery

### ISSUE THREAD

**Issue by adrianwells** [microsoft/ReverseDSC#17]
Attempting to upgrade from 1.9.4.4 to 2.0.0.0 and not yet finding success using commands such as:

`Update-Module -Name ReverseDSC  -Force`
also tried
`Install-Module -Name ReverseDSC -AllowClobber -Force`

Please advise to help resolve and thank you.

**Comment by NikCharlebois** [comment]
@adrianwells Weird, you should be able to do so just by going:

Install-Module ReverseDSC -RequiredVersion 2.0.0.0 -Force

**Comment by adrianwells** [comment]
@NikCharlebois thank you all set with this.
